//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImageOcrText.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class OcrLang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OcrLang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ImageOcrText.Resources.Languages.OcrLang", typeof(OcrLang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agree.
        /// </summary>
        internal static string Agree_Text {
            get {
                return ResourceManager.GetString("Agree_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string ButtonCancel_Text {
            get {
                return ResourceManager.GetString("ButtonCancel_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string ButtonClear_Text {
            get {
                return ResourceManager.GetString("ButtonClear_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string ButtonClose_Text {
            get {
                return ResourceManager.GetString("ButtonClose_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string ButtonCopy_Text {
            get {
                return ResourceManager.GetString("ButtonCopy_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        internal static string ButtonImage_Text {
            get {
                return ResourceManager.GetString("ButtonImage_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picture.
        /// </summary>
        internal static string ButtonPicture_Text {
            get {
                return ResourceManager.GetString("ButtonPicture_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share.
        /// </summary>
        internal static string ButtonShare_Text {
            get {
                return ResourceManager.GetString("ButtonShare_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please close the application..
        /// </summary>
        internal static string CloseApplication_Text {
            get {
                return ResourceManager.GetString("CloseApplication_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright.
        /// </summary>
        internal static string Copyright_Text {
            get {
                return ResourceManager.GetString("Copyright_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert text in an image or photo to editable text..
        /// </summary>
        internal static string Description_Text {
            get {
                return ResourceManager.GetString("Description_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disagree.
        /// </summary>
        internal static string Disagree_Text {
            get {
                return ResourceManager.GetString("Disagree_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail:.
        /// </summary>
        internal static string Email_Text {
            get {
                return ResourceManager.GetString("Email_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string ErrorTitle_Text {
            get {
                return ResourceManager.GetString("ErrorTitle_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optical Character Recognition.
        /// </summary>
        internal static string ImageOcrText_Text {
            get {
                return ResourceManager.GetString("ImageOcrText_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        internal static string Info_Text {
            get {
                return ResourceManager.GetString("Info_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image to text: the text can be edited, copied, shared and read aloud.
        ///Not every language is supported, this depends on the device and installed languages. The font, size, contrast and quality are also important. There is no guarantee that the converted text is correct.
        ///
        ///Text to speech: not all languages are supported that are provided in the application settings.
        ///This option depend from device to device and the installed languages. It is possible that for some languages the translation to speech is done [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string InfoExplanation_Text {
            get {
                return ResourceManager.GetString("InfoExplanation_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language:.
        /// </summary>
        internal static string Language_Text {
            get {
                return ResourceManager.GetString("Language_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language speech:.
        /// </summary>
        internal static string LanguageSpeech_Text {
            get {
                return ResourceManager.GetString("LanguageSpeech_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This application may be used freely for non-commercial purposes.
        ///Use this program entirely at your own risk..
        /// </summary>
        internal static string License_Text {
            get {
                return ResourceManager.GetString("License_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MIT License:
        ///Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the &quot;Software&quot;), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
        ///
        ///The above copyright notice and this permission notice (includi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LicenseMit_Text {
            get {
                return ResourceManager.GetString("LicenseMit_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The software is provided &apos;as is&apos;, without warranty of any kind, express or implied, including but not limited to the warranties of merchantability, fitness for a particular purpose and noninfringement. In no event shall the author and/or publisher be liable for any claim, damages or other liability, whether in an action of contract, tort or otherwise, arising from, out of or in connection with the software or the use or other dealings in the software..
        /// </summary>
        internal static string LicenseMit2_Text {
            get {
                return ResourceManager.GetString("LicenseMit2_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License.
        /// </summary>
        internal static string LicenseTitle_Text {
            get {
                return ResourceManager.GetString("LicenseTitle_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image to Text (OCR).
        /// </summary>
        internal static string NameProgram_Text {
            get {
                return ResourceManager.GetString("NameProgram_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No personal and other data is stored or passed on to myself and others..
        /// </summary>
        internal static string PrivacyPolicy_Text {
            get {
                return ResourceManager.GetString("PrivacyPolicy_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy:.
        /// </summary>
        internal static string PrivacyPolicyTitle_Text {
            get {
                return ResourceManager.GetString("PrivacyPolicyTitle_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings_Text {
            get {
                return ResourceManager.GetString("Settings_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string SettingsReset_Text {
            get {
                return ResourceManager.GetString("SettingsReset_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string SettingsSave_Text {
            get {
                return ResourceManager.GetString("SettingsSave_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save the settings for a next session if necessary..
        /// </summary>
        internal static string SettingsSaved_Text {
            get {
                return ResourceManager.GetString("SettingsSaved_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text to speech is not supported on this device..
        /// </summary>
        internal static string TextToSpeechError_Text {
            get {
                return ResourceManager.GetString("TextToSpeechError_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme:.
        /// </summary>
        internal static string Theme_Text {
            get {
                return ResourceManager.GetString("Theme_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        internal static string ThemeDark_Text {
            get {
                return ResourceManager.GetString("ThemeDark_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        internal static string ThemeLight_Text {
            get {
                return ResourceManager.GetString("ThemeLight_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        internal static string ThemeSystem_Text {
            get {
                return ResourceManager.GetString("ThemeSystem_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel the changes.
        /// </summary>
        internal static string ToolTipCancel_Text {
            get {
                return ResourceManager.GetString("ToolTipCancel_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete the text.
        /// </summary>
        internal static string ToolTipClear_Text {
            get {
                return ResourceManager.GetString("ToolTipClear_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string ToolTipClose_Text {
            get {
                return ResourceManager.GetString("ToolTipClose_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy the text to the clipboard.
        /// </summary>
        internal static string ToolTipCopy_Text {
            get {
                return ResourceManager.GetString("ToolTipCopy_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open an image.
        /// </summary>
        internal static string ToolTipImage_Text {
            get {
                return ResourceManager.GetString("ToolTipImage_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take a picture.
        /// </summary>
        internal static string ToolTipPicture_Text {
            get {
                return ResourceManager.GetString("ToolTipPicture_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset to default settings.
        /// </summary>
        internal static string ToolTipSettingsReset_Text {
            get {
                return ResourceManager.GetString("ToolTipSettingsReset_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save the settings.
        /// </summary>
        internal static string TooltipSettingsSaved_Text {
            get {
                return ResourceManager.GetString("TooltipSettingsSaved_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share the text.
        /// </summary>
        internal static string ToolTipShare_Text {
            get {
                return ResourceManager.GetString("ToolTipShare_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text to speech.
        /// </summary>
        internal static string ToolTipTextToSpeech_Text {
            get {
                return ResourceManager.GetString("ToolTipTextToSpeech_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version:.
        /// </summary>
        internal static string Version_Text {
            get {
                return ResourceManager.GetString("Version_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        internal static string Website_Text {
            get {
                return ResourceManager.GetString("Website_Text", resourceCulture);
            }
        }
    }
}
